import { TextsType } from './types';

export const texts: TextsType = {
  homeLink: 'Home',
  projectsLink: 'Projects',
  contactLink: 'Contact',
  homeIntro: `Hi! I'm Nicolás Rodríguez!`,
  homeProfessional: 'Professional',
  homeWebDev: 'Web Developer',
  homeBio: `Passionate about enhancing user experiences through human-centered, intuitive UI design, leveraging a background in psychology. Proficient in developing complex web applications using HTML, CSS, React, Angular, Node, and Express, with experience in adding value to ongoing projects, providing support, and creating new solutions from scratch using modern technologies under Scrum methodologies.`,
  homeProficient: `Proficient`,
  homeBioCont: `in debugging, code review, and seamless code deployment across diverse environments. Track record of crafting sophisticated applications, prioritizing continuous development and improvement to deliver outstanding results.`,
  homeBio2: `I'm a gamer, board game enthusiast, movie buff, and all-around nerd who speaks English and Spanish fluently. I love to laugh and have fun. Join me on this journey of growth, laughter, and nerdiness!`,
  homeButton: 'Get in touch with me!',
  aboutIntro1: `I'm Nicolas Rodriguez, a professional web developer dedicated to crafting seamless digital experiences. My passion lies in creating impactful solutions that captivate users and drive success.`,
  aboutIntro2: `I bring my skills to life using a powerful combination of technologies like TypeScript, React.js, Node.js, and Git. These tools form the backbone of my work, allowing me to build robust and innovative solutions that elevate user experiences to new heights.`,
  aboutIntro3: `But let's not stop at coding—I'm all about infusing personality and creativity into my projects. When I'm not immersed in lines of code, you'll find me exploring the captivating realm of board games, diving into the latest mind-bending sci-fi novels, or simply savoring the flavors of a perfectly brewed cup of coffee.`,
  aboutIntro4: `Now, here's the exciting part—I'm eager to collaborate and contribute to your goals. Together, we'll turn your vision into a digital reality that shines. So don't hesitate to reach out and let's embark on this thrilling journey of growth and success. I can't wait to connect with you!`,
  aboutTechSkills: 'Technical Skills',
  aboutExp: 'Experience',
  aboutEdu: 'Education',
  aboutGraduation: 'Graduation',
  aboutLinks: 'My Links',
  linksGitHub: 'GitHub',
  linksLinkedIn: 'LinkedIn',
  linksEmailHotmail: 'nicolasrodriguezch@hotmail.com',
  linksEmailGmail: 'nicolasrodriguezch@gmail.com',
  linksResume: 'Check my CV',
  linksPhoneNumber: '+57 300 264 3270',
  linksLocation: 'Bogotá D.C., Colombia',
  projectsErrorTitle: 'Project not found',
  projectsErrorP: `Sorry, we couldn't find the project you're looking for.`,
  projectsButton: 'Go back to projects',
  projectsDescription: 'Project Description',
  projectsLinks: 'Project Links',
  projectsDeployLink: 'Check out the live project',
  notFoundTitle: 'Eror 404 Not Found',
  notFoundText: `It seems like the page you are looking for doesn't exist.`,
  notFoundButton: 'Go back to the Home Page',
};

export const stack: string[] = [
  'TypeScript',
  'JavaScript',
  'NextJS',
  'React.JS',
  'Angular',
  'Node.JS',
  'Express',
  'PostgreSQL',
  'Terraform',
  'AWS',
  'TailwindCSS',
  'SASS',
];

export const ABOUT_PARAGRAPHS: string[] = [
  'aboutIntro1',
  'aboutIntro2',
  'aboutIntro3',
  'aboutIntro4',
];
